# Site settings
name: Dylan Currey
email: dscurrey@outlook.com
canonical_url: https://dscurrey.co.uk
keywords: "Java, C#, NetBeans, Visual Studio, Agile, Student, Computer Science, developer, programmer"
skills: ".NET Developer at razorblue" #"BSc Computer Science Student (Hons) (First Class) Graduate"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/dscurrey/
  - title: github
    url: https://github.com/dscurrey
  - title: github
    url: https://gitea.dcurrey.co.uk/
  # - title: self-hosting-dash
  #   url: https://dash.dcurrey.co.uk/
  # - title: wordpress
  #   url: https://wp.dcurrey.co.uk/

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
